spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: false
  thymeleaf:
    cache: false
    suffix: .html
  mail:
    host: smtp.163.com
    username: firstpersonl@163.com
    password: 1741diswjj
    port: 25